# Generated by Django 5.1.4 on 2025-04-06 16:44

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='menuitem',
            name='type',
            field=models.CharField(blank=True, choices=[('Makanan', 'Makanan'), ('Minuman', 'Minuman')], max_length=10),
        ),
        migrations.AlterField(
            model_name='menuitem',
            name='Bonus',
            field=models.CharField(blank=True, max_length=100),
        ),
    ]
