# Generated by Django 5.1.4 on 2025-04-06 16:58

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0002_menuitem_type_alter_menuitem_bonus'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='menuitem',
            name='Bonus',
        ),
        migrations.RemoveField(
            model_name='menuitem',
            name='type',
        ),
        migrations.AddField(
            model_name='menuitem',
            name='addon_type',
            field=models.CharField(blank=True, choices=[('makanan', 'Makanan'), ('minuman', 'Minuman')], max_length=10),
        ),
    ]
