# Generated by Django 5.1.4 on 2025-04-06 17:10

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0003_remove_menuitem_bonus_remove_menuitem_type_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='menuitem',
            name='addon_type',
        ),
        migrations.AddField(
            model_name='menuitem',
            name='Bonus',
            field=models.CharField(default=1, max_length=100),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='promo',
            name='title',
            field=models.CharField(max_length=100),
        ),
    ]
