# Generated by Django 5.1.4 on 2025-04-06 17:41

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0005_miniitem'),
    ]

    operations = [
        migrations.AddField(
            model_name='miniitem',
            name='item_type',
            field=models.CharField(choices=[('makanan', 'Makanan'), ('minuman', 'Minuman')], default=1, max_length=20),
            preserve_default=False,
        ),
    ]
