# Generated by Django 5.1.4 on 2025-04-15 08:09

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0007_testimonial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='testimonial',
            old_name='comment',
            new_name='message',
        ),
        migrations.RemoveField(
            model_name='testimonial',
            name='delay',
        ),
        migrations.RemoveField(
            model_name='testimonial',
            name='rating',
        ),
        migrations.AddField(
            model_name='testimonial',
            name='photo',
            field=models.ImageField(blank=True, upload_to='testimonial_photos/'),
        ),
        migrations.AddField(
            model_name='testimonial',
            name='stars',
            field=models.PositiveIntegerField(default=5),
        ),
        migrations.AlterField(
            model_name='testimonial',
            name='role',
            field=models.CharField(blank=True, max_length=100),
        ),
    ]
