# Generated by Django 5.1.4 on 2025-05-01 11:47

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0008_rename_comment_testimonial_message_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='menuitem',
            name='price',
            field=models.PositiveIntegerField(),
        ),
        migrations.AlterField(
            model_name='miniitem',
            name='price',
            field=models.PositiveIntegerField(),
        ),
    ]
