# Generated by Django 5.1.4 on 2025-04-06 17:16

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0004_remove_menuitem_addon_type_menuitem_bonus_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='MiniItem',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
                ('description', models.TextField(blank=True)),
                ('price', models.CharField(max_length=20)),
                ('image', models.ImageField(upload_to='mini/')),
            ],
        ),
    ]
